Name: Nginx install on EC2

on:
 push:
   branch:
     -main

jobs:
  deploy:
    name: Install nginx service on EC2
    runs-on:ubuntu-latest

steps:
  -name:checkout EC2
  uses:actions/checkout@v4

  -name:connect EC2 with ssh
  uses:appleboy/ssh-action@v1.0.3

  with:
   host:${{secrtes.EC2}}
   username:${{secrets.EC2_USER}}
   key:${{secrtes.KEY}}
   port:22

   script: |
     sudo apt update -y
     sudo apt install nginx -y
     sudo restart nginx
     sudo enable nginx
    
  
    
